services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    restart: on-failure
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=ptt_rag
      - MYSQL_PASSWORD=ptt_rag
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
    
  mariadb:
    image: mariadb:11.7.2
    container_name: my_mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=ptt_rag
      - MYSQL_PASSWORD=ptt_rag
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
